# Lab Task 01

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

In [47]:
#code here
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr = arr.reshape(3,4)
print("Reshaped array 1: ", arr)

arr2 =  np.array([13,14,15,16,17,18,19,20,21,22,23,24])
arr2 = arr2.reshape(3,4)
print("Reshaped array 2: ", arr2)
array_v = np.concatenate((arr,arr2), axis = 0)
print("Vertical concat: ", array_v) # vertical concat

array_h = np.concatenate((arr,arr2), axis = 1)
print("Horizontal concat: ", array_h) # horizontal concat

Reshaped array 1:  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshaped array 2:  [[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
Vertical concat:  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
Horizontal concat:  [[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]]


# Lab Task 02


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [20]:
#code here
def classifyemails(emails):
  imp = []
  impwords = ["important","asap", "urgent", "emergency"]
  promo = []
  promowords = ["discount", "sale", " buy now", "reduced price"]
  spam = []
  spamwords = ["congratulations", "cash prize", "click here"]

  for i in emails:
    j = i.lower()  # convert to lowercase letters
    for word in impwords:
      if word in j:
        imp.append(i)
        break # one word is enough to classify it in this simple piece of code, hence break if just one word is found

    for word in promowords:
      if word in j:
        promo.append(i)
        break

    for word in spamwords:
      if word in j:
        spam.append(i)
        break
  return imp, promo, spam
emails = ["buy now at 50% reduced price", "The tasks have to be completed by today as it's important. Please replay ASAP.", "Congratulations on winning dark matter! You're set for eternity!", "Buy now with 100% discount", "Emergency! warning for tornado!", "Click here on the provided link to watch free movies"]
imp, promo, spam = classifyemails(emails)
print("Important: ", imp)
print("Promotions: ", promo)
print("Spam: ", spam)



Important:  ["The tasks have to be completed by today as it's important. Please replay ASAP.", 'Emergency! warning for tornado!']
Promotions:  ['buy now at 50% reduced price', 'Buy now with 100% discount']
Spam:  ["Congratulations on winning dark matter! You're set for eternity!", 'Click here on the provided link to watch free movies']


# Lab Task 03

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [33]:
#code here

def translate(word):
  dictionary = {       # dictionary
      "hello": "hola",
      "goodbye": "adiós",
      "thank you": "gracias",
      "yes": "sí",
      "no": "no",
      "cat": "gato",
      "dog": "perro",
      "house": "casa",
      "friend": "amigo",
      "family": "familia",
      "love": "amor",
      "water": "agua",
      "food": "comida",
      "sun": "sol",
      "moon": "luna",
      "tree": "árbol",
      "flower": "flor",
  }

  for key,value in dictionary.items(): # check if word is available or not
    if key == word:
      return value
  return "Not available"

word = ""
while ( word != 'q'): # q to exit
  word = input("Enter the word: ")
  if word != "q":
    translation = translate(word)
    print("Translation: ", translation)

Enter the word: moon
Translation:  luna
Enter the word: sun
Translation:  sol
Enter the word: I
Translation:  Not available
Enter the word: hello
Translation:  hola
Enter the word: bye
Translation:  Not available
Enter the word: q


# Lab Task 04

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

Some tree example

In [ ]:
# import pandas as pd

# # Create a DataFrame to represent a tree
# data = {
#     'node': ['A', 'B', 'C', 'D', 'E', 'F'],
#     'parent': [None, 'A', 'A', 'B', 'B', 'C']
# }
# df = pd.DataFrame(data)

# print(df)


In [ ]:
# pip install networkx


In [ ]:
# import pandas as pd
# import networkx as nx
# import matplotlib.pyplot as plt

# # Create a DataFrame representing edges in a graph
# data = {
#     'from': ['A', 'A', 'B', 'C', 'D'],
#     'to': ['B', 'C', 'D', 'E', 'E']
# }
# edges = pd.DataFrame(data)

# # Create a graph from the edges DataFrame
# G = nx.from_pandas_edgelist(edges, 'from', 'to')

# # Draw the graph
# nx.draw(G, with_labels=True)
# plt.show()

# # Analyze the graph
# print("Nodes:", G.nodes())
# print("Edges:", G.edges())
# print("Degree for each Node:", dict(G.degree()))


In [49]:
import pandas as pd

games = pd.read_csv("/content/vgsalesGlobale.csv") # create Dataframe
games

Rank                                              Name Platform  \
0          1                                        Wii Sports      Wii   
1          2                                 Super Mario Bros.      NES   
2          3                                    Mario Kart Wii      Wii   
3          4                                 Wii Sports Resort      Wii   
4          5                          Pokemon Red/Pokemon Blue       GB   
...      ...                                               ...      ...   
16593  16596                Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                     Men in Black II: Alien Escape       GC   
16595  16598  SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                        Know How 2       DS   
16597  16600                                  Spirits & Spells      GBA   

         Year         Genre   Publisher  NA_Sales  EU_Sales  JP_Sales  \
0      2006.0        Sports    Nintendo     41.49     29.02      3.77   
1      1985.0      Platform    Nintendo     29.08      3.58      6.81   
2      2008.0        Racing    Nintendo     15.85     12.88      3.79   
3      2009.0        Sports    Nintendo     15.75     11.01      3.28   
4      1996.0  Role-Playing    Nintendo     11.27      8.89     10.22   
...       ...           ...         ...       ...       ...       ...   
16593  2002.0      Platform       Kemco      0.01      0.00      0.00   
16594  2003.0       Shooter  Infogrames      0.01      0.00      0.00   
16595  2008.0        Racing  Activision      0.00      0.00      0.00   
16596  2010.0        Puzzle    7G//AMES      0.00      0.01      0.00   
16597  2003.0      Platform     Wanadoo      0.01      0.00      0.00   

       Other_Sales  Global_Sales  
0             8.46         82.74  
1             0.77         40.24  
2             3.31         35.82  
3             2.96         33.00  
4             1.00         31.37  
...            ...           ...  
16593         0.00          0.01  
16594         0.00          0.01  
16595         0.00          0.01  
16596         0.00          0.01  
16597         0.00          0.01  

[16598 rows x 11 columns]

In [71]:
# total global sales

Tglobal_sales = games["Global_Sales"].sum()
print("Total global sales: ", Tglobal_sales)

#game with the highest global sales

highestG_sales_rowIDX= games["Global_Sales"].idxmax() #get index
print("Game with highest global sales: ", games.iloc[highestG_sales_rowIDX]["Name"]) # print required cell

#average sales for each region
#NA_Sales	EU_Sales	JP_Sales	Other_Sales

Avg_NA_Sales	= games["NA_Sales"].mean() # find average
Avg_EU_Sales = games["EU_Sales"].mean()
Avg_JP_Sales = games["JP_Sales"].mean()
Avg_Other_Sales	= games["Other_Sales"].mean()

print("Avg NA_Sales: ", Avg_NA_Sales)
print("Avg EU_Sales: ", Avg_EU_Sales)
print("Avg JP_Sales: ", Avg_JP_Sales)
print("Avg Other_Sales: ", Avg_Other_Sales)



Total global sales:  8920.44
Game with highest global sales:  Wii Sports
Avg NA_Sales:  0.26466742981082064
Avg EU_Sales:  0.14665200626581515
Avg JP_Sales:  0.077781660441017
Avg Other_Sales:  0.0480630196409206


In [94]:
#Find the top 5 most popular game genres based on global sales

groups_by_genre = games.groupby("Genre") # grouby Genre
sales_by_genre = groups_by_genre["Global_Sales"].sum() # find sum of same genres
sales_by_genre = sales_by_genre.sort_values() # sort them
top_five = sales_by_genre.tail(5) # get top five
top_f = top_five[::-1]   # order them right
top_f

Genre
Action          1751.18
Sports          1330.93
Shooter         1037.37
Role-Playing     927.37
Platform         831.37
Name: Global_Sales, dtype: float64

In [100]:
#Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales)

groups_by_genre = games.groupby("Genre")
sales_by_NA_Sales = groups_by_genre["NA_Sales"].sum()
sales_by_EU_Sales = groups_by_genre["EU_Sales"].sum()
sales_by_JP_Sales = groups_by_genre["JP_Sales"].sum()
sales_by_Other_Sales = groups_by_genre["Other_Sales"].sum()

sales_by_NA_Sales = sales_by_NA_Sales.sort_values(ascending = False) # sort in decending order
print(sales_by_NA_Sales.head(1))


Genre
Action    877.83
Name: NA_Sales, dtype: float64


In [70]:
# Display last 10 rows.
print("Last 10 rows: ")
games.tail(10)

Last 10 rows: 


Rank                                               Name Platform  \
16588  16591                                   Mega Brain Boost       DS   
16589  16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV   
16590  16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP   
16591  16594                                Myst IV: Revelation       PC   
16592  16595                                           Plushees       DS   
16593  16596                 Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                      Men in Black II: Alien Escape       GC   
16595  16598   SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                         Know How 2       DS   
16597  16600                                   Spirits & Spells      GBA   

         Year         Genre              Publisher  NA_Sales  EU_Sales  \
16588  2008.0        Puzzle  Majesco Entertainment      0.01      0.00   
16589  2016.0        Action        dramatic create      0.00      0.00   
16590  2007.0  Role-Playing     Falcom Corporation      0.00      0.00   
16591  2004.0     Adventure                Ubisoft      0.01      0.00   
16592  2008.0    Simulation              Destineer      0.01      0.00   
16593  2002.0      Platform                  Kemco      0.01      0.00   
16594  2003.0       Shooter             Infogrames      0.01      0.00   
16595  2008.0        Racing             Activision      0.00      0.00   
16596  2010.0        Puzzle               7G//AMES      0.00      0.01   
16597  2003.0      Platform                Wanadoo      0.01      0.00   

       JP_Sales  Other_Sales  Global_Sales  
16588      0.00          0.0          0.01  
16589      0.01          0.0          0.01  
16590      0.01          0.0          0.01  
16591      0.00          0.0          0.01  
16592      0.00          0.0          0.01  
16593      0.00          0.0          0.01  
16594      0.00          0.0          0.01  
16595      0.00          0.0          0.01  
16596      0.00          0.0          0.01  
16597      0.00          0.0          0.01

In [112]:
#Determine the top 3 gaming platforms with the highest global sales.
groups_by_platforms = games.groupby("Platform")
sales_by_platforms = groups_by_platforms["Global_Sales"].sum().sort_values(ascending = False)
print(sales_by_platforms.head(3))

Platform
PS2     1255.64
X360     979.96
PS3      957.84
Name: Global_Sales, dtype: float64


In [127]:
#Calculate the market share (percentage of global sales) for each genre.
groups_by_genre = games.groupby("Genre")
sales_by_genre = groups_by_genre["Global_Sales"].sum()
total_global_sales = games["Global_Sales"].sum()

print("Total Global sales: ", total_global_sales)

for idx, sales in sales_by_genre.items():
  share = (sales/ total_global_sales) * 100
  print(idx, " Market share: ", (sales/ total_global_sales) * 100)

Total Global sales:  8920.44
Action  Market share:  19.63109443031958
Adventure  Market share:  2.6796884458614145
Fighting  Market share:  5.0323750846370805
Misc  Market share:  9.079821174740259
Platform  Market share:  9.319831757177896
Puzzle  Market share:  2.7459407831900666
Racing  Market share:  8.206321661263345
Role-Playing  Market share:  10.396011855917422
Shooter  Market share:  11.629134885723124
Simulation  Market share:  4.396644111725431
Sports  Market share:  14.920003945993695
Strategy  Market share:  1.9631318634506818


In [128]:
#Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

correlation_coefficient = games["NA_Sales"].corr(games["EU_Sales"]) # use given function
print("correlatin_coefficient: ", correlation_coefficient)

correlatin_coefficient:  0.7677267483702631
